using System.Text;

namespace MGCBConvert;

public class BuilderCodeGenerator
{
    private readonly StringBuilder _sb = new();
    private int _indentLevel = 0;

    public BuilderCodeGenerator()
    {
    }

    public string Generate(MGCBGlobalConfig config, List<ContentGroup> groups)
    {
        _sb.Clear();
        _indentLevel = 0;

        AppendLine("// This file was automatically generated by the MonoGame Content Builder Migration Tool");
        AppendLine($"// from a legacy Content.mgcb file.");
        AppendLine("// ");
        AppendLine("// You may need to adjust some settings or add custom importer/processor references.");
        AppendLine();

        GenerateUsings();
        GenerateMainMethod();
        GenerateBuilderClass(groups);

        return _sb.ToString();
    }

    private void GenerateUsings()
    {
        AppendLine("using Microsoft.Xna.Framework;");
        AppendLine("using Microsoft.Xna.Framework.Content.Pipeline;");
        AppendLine("using Microsoft.Xna.Framework.Content.Pipeline.Processors;");
        AppendLine("using MonoGame.Framework.Content.Pipeline.Builder;");
        AppendLine();
    }

    private void GenerateMainMethod()
    {
        AppendLine("/// <summary>");
        AppendLine("/// Entry point for the Content Builder project,");
        AppendLine("/// which when executed will build content according to the \"Content Collection Strategy\" defined in the Builder class.");
        AppendLine("/// </summary>");
        AppendLine("/// <remarks>");
        AppendLine("/// Make sure to validate the directory paths in the \"ContentBuilderParams\" for your specific project.");
        AppendLine("/// For more details regarding the Content Builder, see the MonoGame documentation: <tbc.>");
        AppendLine("/// </remarks>");
        AppendLine();

        AppendLine("var contentCollectionArgs = new ContentBuilderParams()");
        AppendLine("{");
        _indentLevel++;
        AppendLine("Mode = ContentBuilderMode.Builder,");
        AppendLine("WorkingDirectory = $\"{AppContext.BaseDirectory}../../../\", // path to where your content folder can be located");
        AppendLine("SourceDirectory = \"Assets\", // Not actually needed as this is the default, but added for reference");
        AppendLine("Platform = TargetPlatform.DesktopGL");
        _indentLevel--;
        AppendLine("};");

        AppendLine("var builder = new Builder();");
        AppendLine();

        AppendLine("if (args is not null && args.Length > 0)");
        AppendLine("{");
        _indentLevel++;
        AppendLine("builder.Run(args);");
        _indentLevel--;
        AppendLine("}");
        AppendLine("else");
        AppendLine("{");
        _indentLevel++;
        AppendLine("builder.Run(contentCollectionArgs);");
        _indentLevel--;
        AppendLine("}");
        AppendLine();

        AppendLine("return builder.FailedToBuild > 0 ? -1 : 0;");
        AppendLine();
    }

    private void GenerateBuilderClass(List<ContentGroup> groups)
    {
        AppendLine("public class Builder : ContentBuilder");
        AppendLine("{");
        _indentLevel++;

        AppendLine("public override IContentCollection GetContentCollection()");
        AppendLine("{");
        _indentLevel++;

        AppendLine("ContentCollection contentCollection = new ContentCollection();");
        AppendLine();

        // Generate content rules grouped by type
        GenerateContentRules(groups);

        AppendLine();
        AppendLine("return contentCollection;");

        _indentLevel--;
        AppendLine("}");

        _indentLevel--;
        AppendLine("}");
    }

    private void GenerateContentRules(List<ContentGroup> groups)
    {
        // Group by content root if there are multiple
        Dictionary<string, List<ContentGroup>> byContentRoot = [];
        foreach (ContentGroup group in groups)
        {
            string rootKey = group.ContentRoot ?? "Content";
            if (!byContentRoot.TryGetValue(rootKey, out List<ContentGroup>? value))
            {
                value = new List<ContentGroup>();
                byContentRoot[rootKey] = value;
            }

            value.Add(group);
        }

        bool needsRootChange = byContentRoot.Count > 1;

        foreach (var contentGroup in byContentRoot)
        {
            if (needsRootChange)
            {
                AppendLine($"// Content root: {contentGroup.Key}");
                AppendLine($"contentCollection.SetContentRoot(\"{contentGroup.Key}\");");
                AppendLine();
            }

            List<ContentGroup> copyGroups = new List<ContentGroup>();
            List<ContentGroup> buildGroups = new List<ContentGroup>();

            foreach (ContentGroup group in contentGroup.Value)
            {
                if (group.IsCopyAction)
                {
                    copyGroups.Add(group);
                }
                else
                {
                    buildGroups.Add(group);
                }
            }

            if (copyGroups.Count > 0)
            {
                AppendLine("// Copy operations (files copied without processing)");
                foreach (ContentGroup group in copyGroups)
                {
                    GenerateCopyRule(group);
                }
                AppendLine();
            }

            if (buildGroups.Count > 0)
            {
                Dictionary<string, List<ContentGroup>> byProcessor = [];
                foreach (ContentGroup group in buildGroups)
                {
                    string procKey = group.ProcessorName ?? "Default";
                    if (!byProcessor.TryGetValue(procKey, out List<ContentGroup>? value))
                    {
                        value = new List<ContentGroup>();
                        byProcessor[procKey] = value;
                    }

                    value.Add(group);
                }

                foreach (var procGroup in byProcessor)
                {
                    if (procGroup.Key != "Default")
                    {
                        AppendLine($"// {procGroup.Key} content");
                    }
                    else
                    {
                        AppendLine("// Content using default processors");
                    }

                    foreach (ContentGroup group in procGroup.Value)
                    {
                        GenerateBuildRule(group);
                    }
                    AppendLine();
                }
            }
        }
    }

    private void GenerateCopyRule(ContentGroup group)
    {
        if (group.UseWildcard)
        {
            AppendLine($"contentCollection.IncludeCopy<WildcardRule>(\"{group.Pattern}\");");
        }
        else
        {
            AppendLine($"contentCollection.IncludeCopy(\"{group.Pattern}\", null);");
        }
    }

    private void GenerateBuildRule(ContentGroup group)
    {
        bool hasImporter = !string.IsNullOrEmpty(group.ImporterName);
        bool hasProcessor = !string.IsNullOrEmpty(group.ProcessorName);
        Dictionary<string, string> nonDefaultParams = DefaultProcessorParameters.FilterNonDefaults(group.ProcessorName, group.ProcessorParameters);
        bool hasCustomParams = nonDefaultParams.Count > 0;
        bool needsProcessorInstance = hasCustomParams;

        if (!hasImporter && !hasProcessor)
        {
            if (group.UseWildcard)
            {
                AppendLine($"contentCollection.Include<WildcardRule>(\"{group.Pattern}\");");
            }
            else
            {
                AppendLine($"contentCollection.Include(\"{group.Pattern}\");");
            }
        }
        else if (needsProcessorInstance)
        {
            AppendLine("{");
            _indentLevel++;

            if (hasImporter)
            {
                AppendLine($"var importer = new {group.ImporterName}();");
            }

            if (hasProcessor)
            {
                AppendLine($"var processor = new {group.ProcessorName}");
                AppendLine("{");
                _indentLevel++;

                foreach (var param in nonDefaultParams)
                {
                    string value = FormatParameterValue(param.Key, param.Value);
                    AppendLine($"{param.Key} = {value},");
                }

                _indentLevel--;
                AppendLine("};");
            }

            AppendLine();

            if (group.UseWildcard)
            {
                string importerArg = hasImporter ? "importer" : "null";
                string processorArg = hasProcessor ? "processor" : "null";
                AppendLine($"contentCollection.Include<WildcardRule>(\"{group.Pattern}\", {importerArg}, {processorArg});");
            }
            else
            {
                string importerArg = hasImporter ? "importer" : "null";
                string processorArg = hasProcessor ? "processor" : "null";
                AppendLine($"contentCollection.Include(\"{group.Pattern}\", {importerArg}, {processorArg});");
            }

            _indentLevel--;
            AppendLine("}");
        }
        else
        {
            if (group.UseWildcard)
            {
                string importerArg = hasImporter ? $"new {group.ImporterName}()" : "null";
                string processorArg = hasProcessor ? $"new {group.ProcessorName}()" : "null";
                AppendLine($"contentCollection.Include<WildcardRule>(\"{group.Pattern}\", {importerArg}, {processorArg});");
            }
            else
            {
                string importerArg = hasImporter ? $"new {group.ImporterName}()" : "null";
                string processorArg = hasProcessor ? $"new {group.ProcessorName}()" : "null";
                AppendLine($"contentCollection.Include(\"{group.Pattern}\", {importerArg}, {processorArg});");
            }
        }
    }

    private static string FormatParameterValue(string paramName, string value)
    {
        if (bool.TryParse(value, out bool boolValue))
        {
            return boolValue.ToString().ToLowerInvariant();
        }

        // Color (format: "R,G,B,A")
        if (value.Contains(',') && value.Split(',').Length == 4)
        {
            string[] parts = value.Split(',');

            bool allPartsAreByte = true;
            for (int i = 0; i < parts.Length; i++)
            {
                if (!byte.TryParse(parts[i].Trim(), out _))
                {
                    allPartsAreByte = false;
                    break;
                }
            }

            if (allPartsAreByte)
            {
                string trimmedParts = "";
                for (int i = 0; i < parts.Length; i++)
                {
                    if (i > 0) trimmedParts += ", ";
                    trimmedParts += parts[i].Trim();
                }
                return $"new Color({trimmedParts})";
            }
        }

        // Numeric
        if (int.TryParse(value, out _) || float.TryParse(value, out _) || double.TryParse(value, out _))
        {
            return value;
        }

        // Enum
        if (IsValidIdentifier(value))
        {
            string[] knownEnums =
            [
                "Color",
                "Compressed",
                "DxtCompressed",
                "Dxt5Compressed",
                "NoAlpha",
                "PvrCompressed",
                "Etc1Compressed",
                "AtcCompressed",
                "Best",
                "Low",
                "Auto"
            ];

            bool isKnownEnum = false;
            for (int i = 0; i < knownEnums.Length; i++)
            {
                if (knownEnums[i] == value)
                {
                    isKnownEnum = true;
                    break;
                }
            }

            if (isKnownEnum)
            {
                if (paramName == "TextureFormat")
                {
                    return $"TextureProcessorOutputFormat.{value}";
                }
                else if (paramName == "Quality")
                {
                    return $"ConversionQuality.{value}";
                }
                else if (paramName == "DebugMode")
                {
                    return $"EffectProcessorDebugMode.{value}";
                }
                else if (paramName == "DefaultEffect")
                {
                    return $"MaterialProcessorDefaultEffect.{value}";
                }
            }
        }

        // Default: treat as string
        return $"\"{value}\"";
    }

    private void AppendLine(string text = "")
    {
        if (!string.IsNullOrEmpty(text))
        {
            _sb.Append(new string(' ', _indentLevel * 4));
            _sb.AppendLine(text);
        }
        else
        {
            _sb.AppendLine();
        }
    }

    private static bool IsValidIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return false;
        }

        // First character must be a letter or underscore
        char firstChar = value[0];
        if (!char.IsLetter(firstChar) && firstChar != '_')
        {
            return false;
        }

        // Remaining characters must be letters, digits, or underscores
        for (int i = 1; i < value.Length; i++)
        {
            char c = value[i];
            if (!char.IsLetterOrDigit(c) && c != '_')
            {
                return false;
            }
        }

        return true;
    }
}
